using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PRODUCT.DL.Entities
{
    public class Product : EntityBase
    {
        public Product()
        {
            this.DateEdit = DateTime.Now;
        }
        /// <summary>
        /// Name of product
        /// </summary>
        [Required]
        public string Name { get; set; }
        /// <summary>
        /// Matricule of product
        /// </summary>
        [Required]
        public string Matricule { get; set; }
        /// <summary>
        /// alphanumeric string autogenerated at the time of form creation
        /// </summary>
        [Required]
        public string Slug { get; set; }
        /// <summary>
        /// Date of edition of this product
        /// </summary>
        [Column("Date_Edit")]
        [Required]
        public DateTime DateEdit { get; set; }
    }
}
